language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install tox tox-travis coveralls
script:
  - tox -e lint
  - tox
after_success: coveralls
branches:
  except:
    - /^v[0-9]\./
